### PR TITLE
STSMACOM-667 - All notes on a user record set to pop up should pop up, not just the first

### PR DESCRIPTION
**Pull request by Terala-Priyanka**
## Purpose
Issue: All notes on a user record set to pop up should pop up, not just the first
https://issues.folio.org/browse/STSMACOM-667

## Result
a6bOeHKJTi

### CODE REVIEW

**Review by zburke — COMMENTED** [review]
The changes here look good, but code coverage suffers without any test updates. Do you think it's possible to add a test that covers the multiple-notes situation?

**Comment by Terala-Priyanka** [comment]
> The changes here look good, but code coverage suffers without any test updates. Do you think it's possible to add a test that covers the multiple-notes situation?



> The changes here look good, but code coverage suffers without any test updates. Do you think it's possible to add a test that covers the multiple-notes situation?

After discussing with @BogdanDenis , I got to understand that the tests can be taken care  when we move to Jest+RTL in the future

**Review by BogdanDenis — APPROVED** [review]

**Review by ODanyor — APPROVED** [review]

**Review by Svitlana-Korol — APPROVED** [review]

**Review by mariiaschv — APPROVED** [review]

**Comment by zburke** [comment]
@Terala-Priyanka , we do not plan to migrate SSC to Jest/RTL, so code coverage can be addressed in the scope of the current PR.

**Comment by Terala-Priyanka** [comment]
@zburke 
I will add tests to the PR. Thank you for the confirmation.

**Review by BogdanDenis — APPROVED** [review]

**Review by zburke — APPROVED** [review]
LGTM!

**Comment by zburke** [comment]
@Terala-Priyanka, I'm glad we got this merged! Please choose the "Squash and merge" option in the future. The general rules for merging UI PRs are:
* Never force-push to a branch; that destroys the history on the PR and makes following the conversation really hard, especially if comments refer to commits that no longer exist. 
* Always squash when you merge; this keeps the history tidy on the main branch.
* Always put the Jira slug first on the commit subject so it's easy to see when browsing through history. GitHub truncates long subjects, and "UIU-123 restores last name of user in ..." is more helpful than "restores last name of user in details ..."

**Comment by Terala-Priyanka** [comment]
Sure! Thank you @zburke  :)

**Pull request merged**
