### PR TITLE
STSMACOM-671: Search term isn't persisted in SearchAndSort

### PR DESCRIPTION
**Pull request by Javokhir12**
## Purpose
- In `ui-data-import`, We are saving `searchTerm` to `sessionStorage` and pass it to `<SearchAndSort />` as `query` property of `parentResources` prop. But the problem is that `search box` is getting its initial value from local state `locallyChangedSearchTerm`. The logic is comparing it with `undefined` which is always false because `locallyChangedSearchTerm` has initial value of `""` and never gets initial value from `props`.
- Also when refresh the page `searchTerm` will be lost but searched results are persisted because of url query string.
## Refs
- https://issues.folio.org/browse/STSMACOM-671

### CODE REVIEW

**Comment by Javokhir12** [comment]
@mkuklis in #586, Did you mean browser back button? if so I tested these changes in data-import, it is working as expected.

**Comment by mkuklis** [comment]
@Javokhir12 yes I just mostly want to make sure that by fixing this we don't introduce another issue.

The steps to reproduce it were described here:

https://issues.folio.org/browse/STSMACOM-232

**Comment by Javokhir12** [comment]
> @Javokhir12 yes I just mostly want to make sure that by fixing this we don't introduce another issue.
> 
> The steps to reproduce it were described here:
> 
> https://issues.folio.org/browse/STSMACOM-232
> 
> Would you mind trying your change with ui-inventory?

@mkuklis Thanks. I will test it and post my findings here.

**Comment by Javokhir12** [comment]
@mkuklis Here it is. I also tried to go back with browser buttons and it is working.

https://user-images.githubusercontent.com/89512426/173413435-8bd998d1-2c34-4a2c-8856-ad30840372b1.mp4

**Pull request merged**
