### PR TITLE
`<EntryManager>`: `parseInitialValues` prop works with `resourcePath`

### PR DESCRIPTION
**Pull request by MikeTaylor**
The `parseInitialValues` function is now applied correctly when
`resourcePath` is defined (see STSMACOM-757) so that full records are
loaded from a WSAPI.

Previously, the transformation would be applied to the brief version
of the record before the full record was loaded, so that fields that
occur only in the full version of the record were not transformed.

Also, I have documented these previously undocumented props.

Fixes STSMACOM-761.

### CODE REVIEW

**Comment by mkuklis** [comment]
@MikeTaylor I'm a bit confused by this. In the original implementation, the `parseInitialValues` (if present) was executed in EntryWrapper. I see that you moved it to a lower level `EntrySelector` and it's currently only executing when the `resourcePath` is not present.

I'm curious why was this needed. Shouldn't this be up to the implementer to decide if they want to use `resourcePath` and if so they could omit `parseInitialValues`?

**Comment by MikeTaylor** [comment]
> @MikeTaylor I'm a bit confused by this. In the original implementation, the `parseInitialValues` (if present) was executed in EntryWrapper. I see that you moved it to a lower level `EntrySelector` [...]

I don't think that's quite right. The component hierarchy in `<EntryWrapper>` is a bit odd, but EntryWrapper ends up rendering both EntrySelector go get the detail view, and within EntryForm to get the editing overlay.  EntryWrapper itself handles the parsing of initialValues for the editing form that it invokes directly; and it leaves EntrySelector to do this for the full-record display that _it_ invokes.

> and it's currently only executed when the `resourcePath` is not present.

I don't think that is right, either — at least, it is certainly not intended to be:
```
const ComponentToRender = resourcePath ? ConnectedWrapper : EntryFormComponentWithParsing;
```
sets the component either directly to EntryFormComponentWithParsing, or to ConnectedWrapper; but in the latter case, EntryFormComponentWithParsing still gets invoked (and so does the parsing) because it's passed as the `underlyingComponent` prop.

**Review by mkuklis — APPROVED** [review]
I think this cleared things out for me:

https://github.com/folio-org/stripes-smart-components/pull/1367/commits/c07485760d4ccd30b60fb6c4a85c42651adad7df

Thanks @MikeTaylor!

**Comment by MikeTaylor** [comment]
Thanks, @mkuklis, it's good to get that spurious prop-passing out!

**Comment by NikitaSedyx** [comment]
in props new objects are always created, it makes components to re-render infinitely

**Comment by mkuklis** [comment]
@MikeTaylor please check what @NikitaSedyx is describing.

**Comment by MikeTaylor** [comment]
I assume this is considered to be the cause of https://issues.folio.org/browse/UIHAADM-73?

**Comment by MikeTaylor** [comment]
@NikitaSedyx I assume you are referring to
```
const EntryFormComponentWithParsing = ({ initialValues: iv, ...rest }) => (
      <EntryFormComponent initialValues={parseInitialValues(iv)} {...rest} />
    );
```
But then why is my code that uses this working perfectly? And why is the permissions editing working perfectly on dev1?

**Comment by MikeTaylor** [comment]
It's going to be really hard to debug this if I can't reproduce it!

**Comment by MikeTaylor** [comment]
I'm thinking that if @NikitaSedyx's diagnosis is correct, then `useMemo` might be the medicine.

**Comment by NikitaSedyx** [comment]
> dev1

I have no idea what this env is, but I can easily reproduce it locally with fresh stripes-smart-component

> But then why is my code that uses this working perfectly

talking about this part, it's form, but Details view has issues

> then useMemo might be the medicine.

yep, memoization should help unless initialValues on top level are not re-created, but I believe they are not, otherwise we could notice these rerenders before

**Comment by MikeTaylor** [comment]
New PR incoming in a shortish while.

**Pull request merged**
