### PR TITLE
Fixing breaking tests in Stripes-Smart-Components

### PR DESCRIPTION
**Pull request by K-Felk**
Tests for EditCustomFields component were failing because they rely on
context that now has to be loaded via initialState variable.  Moved the
relevant context data to initialState.

refs: https://github.com/folio-org/ui-users/pull/1465

### CODE REVIEW

**Comment by K-Felk** [comment]
okay, this is a new one...tests are running fine locally but breaking here.  WTF?

**Comment by K-Felk** [comment]
In my previous fix, I didn't remove the old okapi endpoint for module information...here, I did take it out.  I wonder if this test environment is still using it?  I added it back and pushed that up.

**Comment by K-Felk** [comment]
Ayup, that's it.  Remote testing is still using the okapi endpoint for module/interface data.  Now we know.

**Review by zburke — APPROVED** [review]
Smart work. Thank you!

**Review by mkuklis — APPROVED** [review]

**Comment by mkuklis** [comment]
Thank you for fixing this @K-Felk!

**Pull request merged**
